default: &default
  turbo_enabled: true
  CUBA_CODE:                        53
  CHILE_CODE:                       56
  USA_CODE:                         1

alectrico:
        <<: *default

santum:
        <<: *default

